apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-namespace
  labels:
    app: my-app
  annotations: 
    createdBy: "Arun kumar Akula"
    description: "This deployment is created by Arun kumar"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template: 
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
      - name: nginx-container
        image: nginx
        ports: 
        - containerPort: 80
