apiVersion: v1
kind: Pod
metadata:
  name: my-label-pod
  namespace: my-namespace
  labels:
    app: my-app-label
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
